import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  toastContainer: {
    position: "absolute",
    top: 60,
    left: 0,
    right: 0,
    zIndex: 9999,
    alignItems: "center",
    pointerEvents: "none" as any,
  },
  toast: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 30,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  toastEmoji: { fontSize: 20 },
  toastText: { fontFamily: "Inter_700Bold", fontSize: 15, color: "#fff" },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  greeting: { fontFamily: "Inter_400Regular", fontSize: 13, marginBottom: 2 },
  title: { fontFamily: "Inter_700Bold", fontSize: 28 },
  streakCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    marginBottom: 14,
  },
  streakEmoji: { fontSize: 24 },
  streakTitle: { fontFamily: "Inter_700Bold", fontSize: 14 },
  streakSub: { fontFamily: "Inter_400Regular", fontSize: 12, marginTop: 2 },
  streakBadge: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  streakBadgeNum: { fontFamily: "Inter_700Bold", fontSize: 16, color: "#fff" },
  xpCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    gap: 12,
  },
  xpCardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  xpLabel: { fontFamily: "Inter_400Regular", fontSize: 12 },
  xpRankName: { fontFamily: "Inter_700Bold", fontSize: 14 },
  xpHint: { fontFamily: "Inter_400Regular", fontSize: 12, textAlign: "center" },
  statsRow: { flexDirection: "row", gap: 10 },
  statBox: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    padding: 12,
    alignItems: "center",
    gap: 6,
  },
  statIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  statVal: { fontFamily: "Inter_700Bold", fontSize: 20 },
  statLabel: { fontFamily: "Inter_400Regular", fontSize: 11 },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  pulseDot: { width: 8, height: 8, borderRadius: 4 },
  sectionTitle: { fontFamily: "Inter_700Bold", fontSize: 16, flex: 1 },
  bonusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  bonusBadgeText: { fontFamily: "Inter_700Bold", fontSize: 11 },
  countBadge: { fontFamily: "Inter_400Regular", fontSize: 12 },
  featuredCard: { borderRadius: 18, borderWidth: 1.5, padding: 18, gap: 16 },
  featuredTop: { flexDirection: "row", gap: 14, alignItems: "flex-start" },
  featuredIconBox: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  featuredTitle: { fontFamily: "Inter_700Bold", fontSize: 16, lineHeight: 22 },
  featuredDesc: { fontFamily: "Inter_400Regular", fontSize: 13, lineHeight: 18 },
  featuredFooter: { flexDirection: "row", alignItems: "center", gap: 10 },
  diffTag: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  diffTagText: { fontFamily: "Inter_600SemiBold", fontSize: 11 },
  xpTagRow: { flexDirection: "row", alignItems: "center", gap: 3 },
  xpTagText: { fontFamily: "Inter_700Bold", fontSize: 12 },
  startRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  startText: { fontFamily: "Inter_600SemiBold", fontSize: 13 },
  missionTypeIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  missionTitle: { fontFamily: "Inter_600SemiBold", fontSize: 14 },
  missionCat: { fontFamily: "Inter_400Regular", fontSize: 12 },
  missionXP: { fontFamily: "Inter_700Bold", fontSize: 12 },
  missionCard: {
    width: 185,
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    gap: 8,
  },
  missionCardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  missionCardMore: {
    width: 76,
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  missionCardMoreText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 12,
    textAlign: "center",
  },
});
