import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "flex-end",
    paddingBottom: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    gap: 8,
  },
  backBtn: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  headerCenter: { flex: 1, alignItems: "center" },
  headerTitle: { fontFamily: "Inter_700Bold", fontSize: 18 },
  headerSub: { fontFamily: "Inter_400Regular", fontSize: 12, marginTop: 2 },
  center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 12, paddingHorizontal: 32 },
  loadingText: { fontFamily: "Inter_400Regular", fontSize: 14 },
  errorText: { fontFamily: "Inter_400Regular", fontSize: 14, textAlign: "center", lineHeight: 22 },
  retryBtn: { paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12, marginTop: 8 },
  retryBtnText: { fontFamily: "Inter_600SemiBold", fontSize: 14, color: "#fff" },
  podiumCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 18,
    marginBottom: 8,
  },
  podiumTitle: { fontFamily: "Inter_700Bold", fontSize: 16, marginBottom: 16, textAlign: "center" },
  podiumRow: { flexDirection: "row", justifyContent: "space-around" },
  podiumItem: { alignItems: "center", gap: 4, flex: 1 },
  podiumEmoji: { fontSize: 28 },
  podiumName: { fontFamily: "Inter_700Bold", fontSize: 13, textAlign: "center" },
  podiumXP: { fontFamily: "Inter_400Regular", fontSize: 11, textAlign: "center" },
  row: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 14,
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    gap: 12,
  },
  positionCol: { width: 28, alignItems: "center" },
  medalEmoji: { fontSize: 22 },
  positionNum: { fontFamily: "Inter_700Bold", fontSize: 15 },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 12,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarLetter: { fontFamily: "Inter_700Bold", fontSize: 18 },
  userInfo: { flex: 1, gap: 4 },
  nameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  username: { fontSize: 14, flexShrink: 1 },
  metaRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  rankTag: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 6 },
  rankTagText: { fontFamily: "Inter_600SemiBold", fontSize: 10 },
  streakPill: { flexDirection: "row", alignItems: "center" },
  streakPillText: { fontFamily: "Inter_600SemiBold", fontSize: 11, color: "#FF6B35" },
  xpCol: { alignItems: "flex-end", gap: 2 },
  xpVal: { fontFamily: "Inter_700Bold", fontSize: 16 },
  xpLabel: { fontFamily: "Inter_400Regular", fontSize: 10 },
});
