import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pageTitle: { fontFamily: "Inter_700Bold", fontSize: 28 },
  editBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
  },
  editBtnText: { fontFamily: "Inter_600SemiBold", fontSize: 13 },
  heroCard: {
    borderRadius: 24,
    borderWidth: 1.5,
    padding: 24,
    alignItems: "center",
    gap: 14,
  },
  nameBlock: { alignItems: "center", gap: 5 },
  heroName: { fontFamily: "Inter_700Bold", fontSize: 22 },
  heroBio: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    textAlign: "center",
    lineHeight: 18,
  },
  topicPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    marginTop: 2,
  },
  topicPillText: { fontFamily: "Inter_600SemiBold", fontSize: 11 },
  streakRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 14,
    borderWidth: 1,
    width: "100%",
  },
  streakFire: { fontSize: 18 },
  streakText: { fontFamily: "Inter_700Bold", fontSize: 14, flex: 1 },
  streakPill: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 20 },
  streakPillText: { fontFamily: "Inter_600SemiBold", fontSize: 11 },
  anonBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
  },
  anonIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  anonTitle: { fontFamily: "Inter_700Bold", fontSize: 14 },
  anonSub: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
  },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  statCard: {
    width: "47%",
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    alignItems: "center",
    gap: 8,
  },
  statIconBox: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  statVal: { fontFamily: "Inter_700Bold", fontSize: 24 },
  statLabel: { fontFamily: "Inter_400Regular", fontSize: 12 },
  sectionTitle: { fontFamily: "Inter_700Bold", fontSize: 16, marginBottom: 14 },
  rankPath: {
    flexDirection: "row",
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
  },
  rankStep: {
    flex: 1,
    alignItems: "center",
    gap: 6,
    position: "relative",
  },
  rankConnector: {
    position: "absolute",
    top: 20,
    left: "50%",
    width: "100%",
    height: 2,
    zIndex: -1,
  },
  rankCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  currentDot: { width: 6, height: 6, borderRadius: 3, marginTop: -4 },
  rankName: { fontSize: 10, textAlign: "center", lineHeight: 14 },
  rankXP: { fontFamily: "Inter_400Regular", fontSize: 9 },
  certCard: {
    borderRadius: 18,
    borderWidth: 1.5,
    padding: 18,
    gap: 14,
  },
  certHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  certIconBox: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  certBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  certTitle: { fontFamily: "Inter_700Bold", fontSize: 15 },
  certSub: { fontFamily: "Inter_400Regular", fontSize: 12, marginTop: 2 },
  certTrack: { height: 10, borderRadius: 5, overflow: "hidden" },
  certFill: { height: "100%", borderRadius: 5 },
  certText: { fontFamily: "Inter_400Regular", fontSize: 12, textAlign: "center" },
  signOutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
  },
  signOutText: { fontFamily: "Inter_600SemiBold", fontSize: 15 },
});
