import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  wrapper: {
    alignItems: "center",
    gap: 14,
  },
  card: {
    width: "100%",
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
    gap: 14,
    ...Platform.select({
      web: { boxShadow: "0 8px 24px rgba(0,0,0,0.35)" } as any,
      default: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.25,
        shadowRadius: 16,
        elevation: 10,
      },
    }),
  },
  lockedStamp: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    zIndex: 20,
  },
  stampLabel: {
    fontFamily: "Inter_700Bold",
    fontSize: 40,
    letterSpacing: 5,
  },
  verdictOverlay: {
    position: "absolute",
    top: 18,
    zIndex: 10,
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 2.5,
  },
  realOverlay: {
    right: 14,
    borderColor: "#00C851",
    backgroundColor: "#00C85120",
    transform: [{ rotate: "10deg" }],
  },
  fakeOverlay: {
    left: 14,
    borderColor: "#FF3B30",
    backgroundColor: "#FF3B3020",
    transform: [{ rotate: "-10deg" }],
  },
  verdictText: {
    fontFamily: "Inter_700Bold",
    fontSize: 17,
    letterSpacing: 2,
  },
  platformBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  platformName: {
    fontFamily: "Inter_700Bold",
    fontSize: 11,
    letterSpacing: 1,
  },
  platformRight: {
    flex: 1,
    alignItems: "flex-end",
  },
  categoryTag: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  categoryText: {
    fontFamily: "Inter_500Medium",
    fontSize: 10,
  },
  postHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
  },
  postHeaderText: {
    flex: 1,
  },
  accountName: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 14,
  },
  accountHandle: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    marginTop: 1,
  },
  postText: {
    fontFamily: "Inter_400Regular",
    fontSize: 15,
    lineHeight: 23,
  },
  imageTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
  },
  imageTagText: {
    fontFamily: "Inter_500Medium",
    fontSize: 13,
  },
  statsRow: {
    flexDirection: "row",
    gap: 18,
    paddingTop: 12,
    borderTopWidth: 1,
  },
  stat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  statText: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
  },
  cluesArea: {
    gap: 8,
    paddingTop: 12,
    borderTopWidth: 1,
  },
  clue: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    padding: 10,
    borderRadius: 8,
  },
  clueText: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 19,
    flex: 1,
  },
  hintRow: {
    width: "100%",
  },
  xpPenaltyText: {
    position: "absolute",
    right: 16,
    top: -4,
    fontFamily: "Inter_700Bold",
    fontSize: 13,
    color: "#FF3B30",
    pointerEvents: "none",
  },
  hintBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
  },
  hintText: {
    fontFamily: "Inter_600SemiBold",
    fontSize: 13,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
    alignItems: "center",
  },
  verdictBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 2,
  },
  verdictBtnText: {
    fontFamily: "Inter_700Bold",
    fontSize: 14,
    letterSpacing: 1,
  },
  swipeHint: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
});
