import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1 },

  listHeader: { marginBottom: 20 },
  pageTitle: { fontFamily: "Inter_700Bold", fontSize: 28, marginBottom: 4 },
  pageSub: { fontFamily: "Inter_400Regular", fontSize: 14 },

  tabsRow: { flexDirection: "row", gap: 8, marginBottom: 16 },
  tabBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 11,
    borderRadius: 12,
    borderWidth: 1.5,
  },
  tabBtnText: { fontFamily: "Inter_600SemiBold", fontSize: 13 },

  infoBanner: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 16,
  },
  infoBannerIcon: {
    width: 38,
    height: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  infoBannerTitle: { fontFamily: "Inter_700Bold", fontSize: 13 },
  infoBannerText: {
    fontFamily: "Inter_400Regular",
    fontSize: 12,
    lineHeight: 18,
  },

  quickStats: { flexDirection: "row", gap: 10, marginBottom: 20 },
  quickStat: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
  },
  quickStatText: { fontFamily: "Inter_600SemiBold", fontSize: 12 },

  missionSection: { gap: 10, marginBottom: 20 },
  sectionTitle: { fontFamily: "Inter_700Bold", fontSize: 15, marginBottom: 4 },
  missionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
  },
  missionIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  missionMeta: { flex: 1, gap: 3 },
  missionTitle: { fontFamily: "Inter_600SemiBold", fontSize: 14 },
  missionCategory: { fontFamily: "Inter_400Regular", fontSize: 12 },
  missionRight: { alignItems: "flex-end", gap: 4 },
  diffText: { fontFamily: "Inter_600SemiBold", fontSize: 11 },
  xpRow: { flexDirection: "row", alignItems: "center", gap: 3 },
  xpText: { fontFamily: "Inter_700Bold", fontSize: 12 },

  allDoneBox: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 32,
    alignItems: "center",
    gap: 12,
    marginTop: 10,
  },
  allDoneTitle: { fontFamily: "Inter_700Bold", fontSize: 20, textAlign: "center" },
  allDoneSub: { fontFamily: "Inter_400Regular", fontSize: 14, textAlign: "center" },

  simSection: { gap: 14 },
  simInfoBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    marginBottom: 4,
  },
  simInfoText: {
    fontFamily: "Inter_400Regular",
    fontSize: 13,
    lineHeight: 20,
    flex: 1,
  },
  simCard: { borderRadius: 16, borderWidth: 1, padding: 16, gap: 12 },
  simCardTop: { flexDirection: "row", gap: 12, alignItems: "flex-start" },
  simIconBox: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  simMeta: { flex: 1, gap: 4 },
  simTitle: { fontFamily: "Inter_700Bold", fontSize: 15 },
  simDesc: { fontFamily: "Inter_400Regular", fontSize: 13, lineHeight: 19 },
  simCardFooter: { flexDirection: "row", alignItems: "center", gap: 8 },
  catTag: { flex: 1, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  catTagText: { fontFamily: "Inter_500Medium", fontSize: 11 },
  simDiff: { fontFamily: "Inter_600SemiBold", fontSize: 11 },
  simXP: { fontFamily: "Inter_700Bold", fontSize: 12 },

  activeHeader: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 16 },
  /** Lab active ekranında toplam XP'yi gösteren kompakt pill */
  activeXpPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    flexShrink: 0,
  },
  activeXpPillText: {
    fontFamily: "Inter_700Bold",
    fontSize: 12,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  activeHeaderMeta: { flex: 1 },
  activeTitle: { fontFamily: "Inter_700Bold", fontSize: 18 },
  activeSub: { fontFamily: "Inter_400Regular", fontSize: 12, marginTop: 2 },
  instructionBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 14,
  },
  instructionText: { fontFamily: "Inter_400Regular", fontSize: 13, flex: 1 },

  resultPage: { flex: 1 },
  resultCard: {
    borderRadius: 18,
    borderWidth: 1.5,
    padding: 18,
    alignItems: "center",
    gap: 10,
  },
  resultIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  resultHeadline: { fontFamily: "Inter_700Bold", fontSize: 20 },
  resultMission: { fontFamily: "Inter_600SemiBold", fontSize: 14, textAlign: "center" },
  xpEarnedBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1.5,
  },
  xpEarnedText: { fontFamily: "Inter_700Bold", fontSize: 16 },
  verdictBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    width: "100%",
  },
  verdictLabel: { fontFamily: "Inter_400Regular", fontSize: 13 },
  verdictTag: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  verdictTagText: { fontFamily: "Inter_700Bold", fontSize: 12 },
  explanationText: {
    fontFamily: "Inter_400Regular",
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
  },
  resultActions: { gap: 16, marginTop: 8 },
  resultActionBar: { paddingTop: 18, borderTopWidth: 1 },
  nextBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 16,
    borderRadius: 16,
  },
  nextBtnText: { fontFamily: "Inter_700Bold", fontSize: 16 },
  listBtn: {
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  listBtnText: { fontFamily: "Inter_600SemiBold", fontSize: 15 },
});
